# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation
# 10. resource data 

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: 240155787 # jekyll-seo-tag > Owners twitter username
author: WeileiZeng # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Weilei Zeng # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/240155787
    - https://www.facebook.com/weilei.zeng
    - https://www.linkedin.com/in/weilei-zeng-032600111
    - https://github.com/weileizeng
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Los_Angeles # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    #description: "My thoughts and ideas" # The post list page content
    #feature_text: |
    #  Welcome to the blog
    #feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Weilei Zeng" # Site name or title, also used in jekyll-seo-tag
#logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
logo: "/assets/weilei-logo.png" # Site logo, also used in jekyll-seo-tag
description: "Website for Weilei Zeng. Forked from Alembic" # Site description and default description, also used in jekyll-seo-tag
url: "https://weileizeng.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/weileizeng/alembic-weilei"
email: "weilei.zeng@foxmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Resume
  url: /resume/
- title: Publications
  url: /publications/
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Resource
  url: /resource/
- title: Search
  url: /search/
#- title: Elements
#  url: /elements/
#- title: Fork Alembic
#  url: https://github.com/daviddarnes/alembic

navigation_footer:
- title: The world is unitary.
  url: https://weileizeng.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/240155787
  LinkedIn: https://www.linkedin.com/in/weilei-zeng-032600111
  GitHub: https://github.com/weileizeng
  link: https://weileizeng.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true


# 10. resource data
topics:
  - name: quantum computing report
    web_url: https://quantumcomputingreport.com/
    image_url: https://secureservercdn.net/184.168.47.225/80b.bf1.myftpupload.com/wp-content/uploads/2016/03/Block-Sphere-Large.bmp
  - name: IBM quantum simulator/devices
    web_url: https://quantum-computing.ibm.com/
    image_url: https://quantum-computing.ibm.com/img/intro.c96a9d64.png

  - name: Quantum circuit visualization - qasm2circ
    web_url: https://www.media.mit.edu/quanta/qasm2circ/
    image_url: https://www.media.mit.edu/quanta/qasm2circ/test1.png


  - name: Open-Source Quantum Software Projects
    web_url: https://github.com/qosf/awesome-quantum-software
    image_url: https://raw.githubusercontent.com/qosf/awesome-quantum-software/master/hopf_fibration.png

  - name: SciRate
    web_url: https://scirate.com/
    image_url: https://scirate.com/assets/scirate-logo-white-on-blue-670e4f99529271708e59ae4485cad9bb.png

people:
  - name: John Preskill
    web_url: http://www.theory.caltech.edu/people/preskill/
    image_url: http://www.theory.caltech.edu/people/preskill/index_files/image002.jpg

  - name: Michael Nielsen
    web_url: http://michaelnielsen.org/
    image_url: http://michaelnielsen.org/images/mn.jpg

  - name: Daniel Gottesman
    web_url: https://www.perimeterinstitute.ca/personal/dgottesman/index.html

  - name: Scott Aaronson
    web_url: https://www.scottaaronson.com/
    image_url: https://www.scottaaronson.com/aarsmall.gif

  - name: Daniel Lidar
    web_url: http://qserver.usc.edu/
    image_url: http://qserver.usc.edu/wordpress/wp-content/uploads/2013/04/Lidar-photo-182x209.jpg

  - name: Kenneth Brown
    web_url: http://brownlab.pratt.duke.edu/
    image_url: https://brownlab.pratt.duke.edu/sites/brownlab.pratt.duke.edu/files/scholars_images/thumb_image_5009222.png

links:
  - name: UCR physics
    web_url: https://physics.ucr.edu/colloquia-seminars

  - name: IQIM @CalTech
    web_url: https://www.caltech.edu/campus-life-events/master-calendar/filter?date_start=&date_end=&type=all&search=&past=0&mc=1&series=420
    description: The Institute for Quantum Information and Matter

  - name: CMP @CalTech
    web_url: http://www.cmp.caltech.edu/seminars.html
    description: Condensed Matter Physics

  - name: IQI @CaleTech
    web_url: https://iqim.caltech.edu/iqi-seminars/
    description: Institute for Quantum Information Weekly Seminars
  - name: More Colloquiua Within Southern California 
    web_url: https://condensedmatter.ucr.edu/resources.html

it:
  - name: 山月行
    web_url: https://shanyue.tech/
  - name: 静觅 - 崔庆才的个人站点
    web_url: https://cuiqingcai.com/
  - name: github tootset
    web_url: https://help.github.com/en